CREATE DATABASE IF NOT EXISTS r57w6qhdgndr95mv;

USE r57w6qhdgndr95mv;

DROP TABLE IF EXISTS storage;

CREATE TABLE storage
(
id int NOT NULL AUTO_INCREMENT,
PRIMARY KEY(id),
link VARCHAR(255),
item VARCHAR(255),
stock VARCHAR(255)
);  

