CREATE DATABASE IF NOT EXISTS l80k3j1waol9ialw;

USE l80k3j1waol9ialw;

DROP TABLE IF EXISTS storage;

CREATE TABLE storage
(
id int NOT NULL AUTO_INCREMENT,
PRIMARY KEY(id),
link VARCHAR(255),
item VARCHAR(255),
stock VARCHAR(255)
);  

